// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var BasicMap = require("./BasicMap");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function make(children) {
  return ReasonReact.wrapJsForReason(BasicMap.default, { }, children);
}

exports.make = make;
/* ./BasicMap Not a pure module */
