// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Fetcher = require("./Fetcher.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSimpleMaps = require("./ReactSimpleMaps.bs.js");

var component = ReasonReact.statelessComponent("Main");

var myStyle = {
  height: "auto",
  width: "100%"
};

var geographyComponentStyle = {
  height: "auto",
  width: "100%"
};

var geographyStyles = Curry._3(ReactSimpleMaps.GeographyComponent[/* Style */0][/* make */0], {
      outline: "none",
      fill: "#ECEFF1",
      stroke: "#607D8B",
      strokeWidth: "0.75"
    }, {
      outline: "none",
      fill: "#607D8B",
      stroke: "#607D8B",
      strokeWidth: "0.75"
    }, {
      outline: "none",
      fill: "#FF5722",
      stroke: "#607D8B",
      strokeWidth: "0.75"
    });

var projectionConfig = Curry._2(ReactSimpleMaps.ComposableMap[/* ProjectionConfig */0][/* make */0], 205, /* array */[
      -11,
      0,
      0
    ]);

function mapGeographies(geographies, projection) {
  return Belt_Array.mapWithIndex(geographies, (function (i, geography) {
                return ReasonReact.element(/* Some */[String(i)], /* None */0, ReactSimpleMaps.GeographyComponent[/* make */2](geography, projection, geographyStyles, /* array */[]));
              }));
}

function fetchUsers() {
  console.log("hello!");
  return Fetcher.fetchGet("https://immense-river-25513.herokuapp.com/locations", (function (users) {
                console.log("users", users);
                return /* () */0;
              }));
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              Fetcher.fetchPost("https://immense-river-25513.herokuapp.com/add-location", "rafacm");
              fetchUsers(/* () */0);
              var intervalId = setInterval(fetchUsers, 30000);
              return Curry._1(self[/* onUnmount */4], (function () {
                            clearInterval(intervalId);
                            return /* () */0;
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("h1", undefined, "Dojo Vienna"), React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, ReactSimpleMaps.ComposableMap[/* make */2](projectionConfig, 980, 551, /* Some */[myStyle], /* array */[ReasonReact.element(/* None */0, /* None */0, ReactSimpleMaps.ZoomableGroup[/* make */1](/* array */[
                                                0,
                                                20
                                              ], true, /* array */[ReasonReact.element(/* None */0, /* None */0, ReactSimpleMaps.Geographies[/* make */1]("/world-50m.json", mapGeographies))]))]))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.myStyle = myStyle;
exports.geographyComponentStyle = geographyComponentStyle;
exports.geographyStyles = geographyStyles;
exports.projectionConfig = projectionConfig;
exports.mapGeographies = mapGeographies;
exports.fetchUsers = fetchUsers;
exports.make = make;
/* component Not a pure module */
