// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSimpleMaps = require("react-simple-maps");

function make(prim, prim$1) {
  return {
          scale: prim,
          rotation: prim$1
        };
}

var ProjectionConfig = /* module */[/* make */make];

function make$1(prim, prim$1, prim$2, prim$3, _) {
  var tmp = {
    projectionConfig: prim,
    width: prim$1,
    height: prim$2
  };
  if (prim$3) {
    tmp.style = prim$3[0];
  }
  return tmp;
}

var Props = /* module */[/* make */make$1];

function make$2(projectionConfig, width, height, style, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.ComposableMap, make$1(projectionConfig, width, height, style, /* () */0), children);
}

var ComposableMap = /* module */[
  /* ProjectionConfig */ProjectionConfig,
  /* Props */Props,
  /* make */make$2
];

function make$3(prim, prim$1) {
  return {
          center: prim,
          disablePanning: prim$1
        };
}

var Props$1 = /* module */[/* make */make$3];

function make$4(center, disablePanning, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.ZoomableGroup, {
              center: center,
              disablePanning: disablePanning
            }, children);
}

var ZoomableGroup = /* module */[
  /* Props */Props$1,
  /* make */make$4
];

var Projection = /* module */[];

function make$5(prim) {
  return {
          id: prim
        };
}

var Geography = /* module */[/* make */make$5];

function make$6(prim) {
  return {
          geography: prim
        };
}

var Props$2 = /* module */[/* make */make$6];

function make$7(geography, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.Geographies, {
              geography: geography
            }, children);
}

var Geographies = /* module */[
  /* Props */Props$2,
  /* make */make$7
];

function make$8(prim, prim$1, prim$2) {
  return {
          default: prim,
          hover: prim$1,
          pressed: prim$2
        };
}

var Style = /* module */[/* make */make$8];

function make$9(prim, prim$1, prim$2) {
  return {
          geography: prim,
          projection: prim$1,
          style: prim$2
        };
}

var Props$3 = /* module */[/* make */make$9];

function make$10(geography, projection, style, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.Geography, {
              geography: geography,
              projection: projection,
              style: style
            }, children);
}

var GeographyComponent = /* module */[
  /* Style */Style,
  /* Props */Props$3,
  /* make */make$10
];

exports.ComposableMap = ComposableMap;
exports.ZoomableGroup = ZoomableGroup;
exports.Projection = Projection;
exports.Geography = Geography;
exports.Geographies = Geographies;
exports.GeographyComponent = GeographyComponent;
/* ReasonReact Not a pure module */
