// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSimpleMaps = require("react-simple-maps");

function make(prim, prim$1) {
  return {
          scale: prim,
          rotation: prim$1
        };
}

var ProjectionConfig = /* module */[/* make */make];

function make$1(prim, prim$1, prim$2, prim$3, _) {
  var tmp = {
    projectionConfig: prim,
    width: prim$1,
    height: prim$2
  };
  if (prim$3) {
    tmp.style = prim$3[0];
  }
  return tmp;
}

var Props = /* module */[/* make */make$1];

function make$2(projectionConfig, width, height, style, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.ComposableMap, make$1(projectionConfig, width, height, style, /* () */0), children);
}

var ComposableMap = /* module */[
  /* ProjectionConfig */ProjectionConfig,
  /* Props */Props,
  /* make */make$2
];

function make$3(prim, prim$1) {
  return {
          center: prim,
          disablePanning: prim$1
        };
}

var Props$1 = /* module */[/* make */make$3];

function make$4(center, disablePanning, children) {
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.ZoomableGroup, {
              center: center,
              disablePanning: disablePanning
            }, children);
}

var ZoomableGroup = /* module */[
  /* Props */Props$1,
  /* make */make$4
];

exports.ComposableMap = ComposableMap;
exports.ZoomableGroup = ZoomableGroup;
/* ReasonReact Not a pure module */
